KEEPALIVED_AUTH_PASS: "ZqSj#f1Gsdf"
KEEPALIVED_VIRTUAL_IPASSRESS: "192.168.0.100"

PROD_NETWORK_CIDR: "10.244.0.0/16"
CONTROL_PLAN_ENDPOINT: "192.168.0.160"
CONTROL_PLAN_ENDPOINT_PORT: 8888
SERVICE_DNS_DOMAIN: "minkovs.ru"
