CRIO_VERSION: "1.28"
OS: "xUbuntu_22.04"
K8S_VERSION: "1.31"
CILIUM_CLI_VERSION: "v0.16.21"
BGP_PEER_ADDRESS: "192.168.0.1/32"
BGP_PEER_ASN: "64512"
HELM_VER: "3.16.3"
INGRESS_CHART_VERSION_VER: "4.7.5"
CERT_MANAGER_VER: "1.16.2"
OH_MY_POSH_VER: "24.12.0"

DOMAIN: "minkovs.ru"

LONGHORN_USER: admin
LONGHORN_PASS: admin

ARGOCD_PASS: "admin"

# Настройка локального proxy репозитория для CRI-O
REGISTRY_PROXY: "192.168.0.14"
REGISTRY_PROXY_PORT: 5010
REGISTRY_PROXY_USER: ""
REGISTRY_PROXY_PASS: ""
