apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics-agent
  namespace: argo-cd
spec:
  destination:
    namespace: monitoring
    name: in-cluster
  project: otus
  source:
    repoURL: git@192.168.0.42:minkovav/otus.git
    path: argocd/HelmCharts/victoriametrics-agent
    targetRevision: master                            #Ветка
    helm:
      valueFiles:
        - victoriametrics-agent-values.yaml
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true