apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmalert
  namespace: argo-cd
spec:
  destination:
    namespace: monitoring
    name: in-cluster
  project: otus
  source:
    repoURL: git@192.168.0.42:minkovav/otus.git
    path: argocd/HelmCharts/vmalert
    targetRevision: master                            #Ветка
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true